name: Azure App Service - gymfitbulgaria-api(Production), Build and deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  backend-redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Terraform Folder'
        uses: actions/checkout@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: "Terraform Init -Main"
        working-directory: ./infra
        run: terraform init

      - name: "Terraform Destroy Targeting Specific Resources -Main"
        working-directory: ./infra
        run: terraform destroy -auto-approve -target=azurerm_windows_web_app.awwabs

      - name: "Terraform Apply Targeting Specific Resources -Main"
        working-directory: ./infra
        run: terraform apply -auto-approve -target=azurerm_windows_web_app.awwabs

#      - name: "Terraform Init -Firewall Rules"
#        working-directory: ./infra/firewallRules
#        run: terraform init
#
#      - name: "Terraform Apply Targeting Specific Resources -Firewall Rules"
#        working-directory: ./infra/firewallRules
#        run: terraform apply -auto-approve -target=azurerm_postgresql_flexible_server_firewall_rule.firewall_rules

      - name: "Set up Git"
        run: |
          git config --global user.name "${{ secrets.WEB_APP_GITHUB_ACTION_USER_NAME}}"
          git config --global user.email "${{ secrets.WEB_APP_GITHUB_ACTION_USER_EMAIL}}"

      - name: "Commit and Push State File"
        run: |
          git pull origin main
          git add .
          git commit -m "Update terraform.tfstate files after modifications"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.LOGIN_AUTH_TOKEN}}

      - name: 'Set up Java version'
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: 'Build with Maven and skip testing'
        run: mvn clean install -DskipTests

      - name: 'Fetch Azure Web App Publish Profile'
        id: fetch-publish-profile
        run: |
          az webapp deployment list-publishing-credentials --name ${{ secrets.WEB_APP_NAME }} --resource-group ${{ secrets.WEB_APP_RESOURCE_GROUP_NAME }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy Spring Boot App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}
          slot-name: 'Production'
          package: 'target/*.jar'
          publish-profile: ${{ steps.fetch-publish-profile.outputs.publish_profile }}